### ISSUE TITLE
Setup Kanban board

### ISSUE THREAD

**Issue by Behnam1369** [Behnam1369/Recipe-app#8]
Please kindly find the link to the project [here](https://github.com/Behnam1369/Recipe-app/projects/1).

**Comment by keneogu** [comment]
Sorry for the late reply. I'm marking this as invalid. Add information about the number of people in the group and submit for review

**Comment by Behnam1369** [comment]
We are a group of two people.

**Comment by Mihndim2020** [comment]
### Hi Team, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Great job so far with the `Kanban board`.

There are some issues that you still need to work on to get this project approved, but you are almost there!
![ALMOST-MINION](https://user-images.githubusercontent.com/65852621/133680327-431cb21d-ad7c-483a-84eb-21b733980a04.png)


# Status: Requires Changes ♻️
_Check the comments below and under the review._

- [ ] As per the [requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md#project-requirements) of this project, " `General shopping list view (do not implement if in group of 3): ` ", please kindly add this requirement in your `Kanban board`, so as to ensure it is implemented during the implementation phase. Since there are only two of you in your group. 

- [ ] Some of your tasks on the `Kanban board` are missing descriptions, tasks like: `Login and registration page`, `Navigation menu`, `N+1 queries happening`, please kindly add a description to this tasks as this will help during the implementation phase to know exactly what you need to implement. 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Behnam1369** [comment]
@Mihndim2020 Thanks for your accuracy.

**Comment by keneogu** [comment]
Hi @Behnam1369, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
